### ISSUE TITLE
bug: semgrep download incompatible with `--sarif`

### ISSUE THREAD

**Issue by indecisivedragon** [crashappsec/chalk#92]
## Description

if `run_sast_tools` is enabled, and semgrep is not found, chalk will attempt to download semgrep with `python3 -m pip install semgrep` which will download version 1.46.0. However chalk also tries to run semgrep with the `--sarif` flag, which is not compatible with version 1.46.0: https://github.com/semgrep/semgrep/issues/9091

## Impact

semgrep (and therefore `run_sast_tools`) is unusable at the moment

## Steps to Reproduce

1. load chalk with a config that has `run_sast_tools: true`
2. run chalk on any binary
3. observe that chalk fails (though this doesn't show you the error)
4. manually run the command that chalk runs: `semgrep ci --config=auto --sarif`
5. observe semgrep error:
```
Object of type ErrorType is not JSON serializable
Traceback (most recent call last):
  File "/home/liming/.local/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/home/liming/.local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 539, in ci
    output_handler.output(
  File "/home/liming/.local/lib/python3.10/site-packages/semgrep/output.py", line 345, in output
    output = self._build_output()
  File "/home/liming/.local/lib/python3.10/site-packages/semgrep/output.py", line 483, in _build_output
    return self.formatter.output(
  File "/home/liming/.local/lib/python3.10/site-packages/semgrep/formatter/base.py", line 28, in output
    return self.format(
  File "/home/liming/.local/lib/python3.10/site-packages/semgrep/formatter/sarif.py", line 445, in format
    return json.dumps(output_dict, sort_keys=True, indent=2)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ErrorType is not JSON serializable
```

**Comment by aryx** [comment]
should work with 1.48.0
